name: Subdomain Watcher (CertStream)

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/10 * * * *"  # запускає кожні 10 хв для стабільності

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CertStream monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
        run: python main.py
